import { describe, test, expect } from 'vitest';
import { render, screen, fireEvent } from '@testing-library/react';
import img from '../../assets/mock-cards/miw-scoring.jpg';
import React from 'react';
import { ContactUs } from './contact-us';
import { Blob } from 'buffer';
describe('component <ContactUs/>', () => {
  test('component renders', () => {
    const component = render(<ContactUs />);
    expect(component).toBeTruthy();
    expect(screen.getByText(/please touch the contact with us/i)).toBeTruthy();
  });
  test('add card from form data', () => {
    const component = render(<ContactUs />);
    expect(component).toBeTruthy();
    const name = screen.getByRole('name') as HTMLInputElement;
    expect(name).toBeTruthy();
    fireEvent.change(name, { target: { value: 'Jessie' } });
    const surname = screen.getByRole('surname') as HTMLInputElement;
    expect(surname).toBeTruthy();
    fireEvent.change(surname, { target: { value: 'Jex' } });
    const email = screen.getByRole('email');
    expect(email).toBeTruthy();
    fireEvent.change(email, { target: { value: 'fantasy@gmail.com' } });
    const date = screen.getByRole('input-date');
    expect(date).toBeTruthy();
    fireEvent.change(date, { target: { value: '1997-2-2' } });
    const radios = screen.getAllByRole('radio');
    expect(radios.length).toBe(2);
    fireEvent.click(radios[0], { target: { checked: true } });
    const options = screen.getAllByRole('option') as HTMLOptionElement[];
    expect(options.length).toBeGreaterThan(2);
    const select = screen.getByRole('combobox');
    expect(select).toBeTruthy();
    fireEvent.change(select, { target: { value: 'Good' } });
    const file = screen.getByRole('input-file');
    expect(file).toBeTruthy();
    const blobFile = new Blob([`${img}`], { type: 'image/jpg' });
    fireEvent.change(file, { target: { files: [blobFile] } });
    const checkbox = screen.getByRole('checkbox') as HTMLInputElement;
    expect(checkbox).toBeTruthy();
    fireEvent.click(checkbox, { target: { checked: true } });
    expect(checkbox.checked).toBe(true);
    const btn = screen.getByText(/create card/i);
    fireEvent.click(btn);
    const card = screen.getByText('Name: Jessie');
    expect(card).toBeTruthy();
  });
});
